# Generated by Django 4.2.1 on 2023-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('credit_card_number', models.IntegerField()),
                ('created_timestamp', models.DateField()),
            ],
        ),
    ]
