# Generated by Django 4.2.1 on 2023-06-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_timestamp',
            field=models.DateField(help_text='N/A'),
        ),
        migrations.AlterField(
            model_name='users',
            name='credit_card_number',
            field=models.IntegerField(help_text='CREDIT_CARD_NUMBER'),
        ),
        migrations.AlterField(
            model_name='users',
            name='useremail',
            field=models.EmailField(help_text='EMAIL_ADDRESS', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(help_text='USERNAME', max_length=255),
        ),
    ]
